/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.nathanmauro.flink.streaming.etl.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DmsEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6718502242473013415L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DmsEvent\",\"namespace\":\"io.nathanmauro.flink.streaming.etl.events\",\"fields\":[{\"name\":\"metadata\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"data\",\"type\":{\"type\":\"map\",\"values\":[\"string\",\"int\",\"float\",\"double\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DmsEvent> ENCODER =
      new BinaryMessageEncoder<DmsEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DmsEvent> DECODER =
      new BinaryMessageDecoder<DmsEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<DmsEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<DmsEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DmsEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this DmsEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a DmsEvent from a ByteBuffer. */
  public static DmsEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Object> data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DmsEvent() {}

  /**
   * All-args constructor.
   * @param metadata The new value for metadata
   * @param data The new value for data
   */
  public DmsEvent(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata, java.util.Map<java.lang.CharSequence,java.lang.Object> data) {
    this.metadata = metadata;
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return metadata;
    case 1: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: metadata = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 1: data = (java.util.Map<java.lang.CharSequence,java.lang.Object>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return The value of the 'metadata' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
    return metadata;
  }

  /**
   * Sets the value of the 'metadata' field.
   * @param value the value to set.
   */
  public void setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.metadata = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Object> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.Map<java.lang.CharSequence,java.lang.Object> value) {
    this.data = value;
  }

  /**
   * Creates a new DmsEvent RecordBuilder.
   * @return A new DmsEvent RecordBuilder
   */
  public static io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder newBuilder() {
    return new io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder();
  }

  /**
   * Creates a new DmsEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DmsEvent RecordBuilder
   */
  public static io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder newBuilder(io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder other) {
    return new io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder(other);
  }

  /**
   * Creates a new DmsEvent RecordBuilder by copying an existing DmsEvent instance.
   * @param other The existing instance to copy.
   * @return A new DmsEvent RecordBuilder
   */
  public static io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder newBuilder(io.nathanmauro.flink.streaming.etl.events.DmsEvent other) {
    return new io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder(other);
  }

  /**
   * RecordBuilder for DmsEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DmsEvent>
    implements org.apache.avro.data.RecordBuilder<DmsEvent> {

    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;
    private java.util.Map<java.lang.CharSequence,java.lang.Object> data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.metadata)) {
        this.metadata = data().deepCopy(fields()[0].schema(), other.metadata);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.data)) {
        this.data = data().deepCopy(fields()[1].schema(), other.data);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DmsEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(io.nathanmauro.flink.streaming.etl.events.DmsEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.metadata)) {
        this.metadata = data().deepCopy(fields()[0].schema(), other.metadata);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.data)) {
        this.data = data().deepCopy(fields()[1].schema(), other.data);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'metadata' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
      return metadata;
    }

    /**
      * Sets the value of the 'metadata' field.
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.metadata = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'metadata' field.
      * @return This builder.
      */
    public io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.Object> getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder setData(java.util.Map<java.lang.CharSequence,java.lang.Object> value) {
      validate(fields()[1], value);
      this.data = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public io.nathanmauro.flink.streaming.etl.events.DmsEvent.Builder clearData() {
      data = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DmsEvent build() {
      try {
        DmsEvent record = new DmsEvent();
        record.metadata = fieldSetFlags()[0] ? this.metadata : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[0]);
        record.data = fieldSetFlags()[1] ? this.data : (java.util.Map<java.lang.CharSequence,java.lang.Object>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DmsEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<DmsEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DmsEvent>
    READER$ = (org.apache.avro.io.DatumReader<DmsEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
